### ISSUE TITLE
On completing some changes in csv

### ISSUE THREAD

**Issue by LehmanITR** [mike-levenick/mut#11]
I have used MUT successfully a number of times, but with a csv with 57 entries, it only completed 12 and gave a 409 error on rest. It threw the error on first 8 then completed task on 5, etc, etc.

What is 409 error and is there a number of entries limit?

**Comment by mike-levenick** [comment]
Hello @LehmanITR . 409 is "conflict" and it can be caused by a number of different things.

There should not be a limit, especially not at ~57 entries--there are folks who use MUT to update thousands of lines. 

If you are getting conflict errors on some lines, I suggest enabling "advanced debugging" in the menu bar at the top, then running the updates again, and then saving the log file and posting it here (or just copy and paste the contents out of the text box in MUT). 

What are you trying to update? The top of the log file/text output should tell us that as well, which will be hugely helpful. Just copy and paste the WHOLE output, and I'll take a look.

**Comment by LehmanITR** [comment]
URL: https://jss.xxxxxx.xxx:8443/
Credentials Successfully Verified.

Device Type: macOS Devices
ID Type: Serial Number
Attribute Type: ADD TO macOS Static Group

CSV: /Users/mike/Desktop/57 Computers in All Art.csv
Found 58 rows in the CSV.

Example row from your CSV:
SerialNumber: C02NT8D2FY14, ADD TO macOS Static Group: 165

==================================================
Please review the above information. If everything looks good, press the submit button. Otherwise, please verify the dropdowns and your CSV file and run another pre-flight check.
==================================================
CSV: /Users/mike/Desktop/57 Computers in All Art.csv
Found 58 rows in the CSV.

Example row from your CSV:
SerialNumber: C02NT8D2FY14, ADD TO macOS Static Group: 165

Device Type: macOS Devices
ID Type: Serial Number
Attribute Type: ADD TO macOS Static Group

Beginning Update Run!

Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Not Found</p>
<p>The server has not found anything matching the request URI</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.5">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber Serial Number - Failed! - 404!

HTTP 404 means 'not found'. There is no device with serialnumber Serial Number enrolled in Jamf Pro.

Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:564, Name:c42A-5k03) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber C02NT8D2FY14 - Failed! - 409!
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:1202, Name:FA_009_X6762) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber C02T72ELGG77 - Failed! - 409!
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:1243, Name:FA_009JE) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber C02TKAPVGVC1 - Failed! - 409!
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:1197, Name:FA_014_X6796) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber C02T72ATGG77 - Failed! - 409!
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:1239, Name:FA_014_X6796) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber D25TL090GQ18 - Failed! - 409!
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:1196, Name:FA_017X8258) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber C02T72F0GG77 - Failed! - 409!
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:1203, Name:FA_034_X8889) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber D25TL0RFGQ18 - Failed! - 409!
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:1205, Name:FA_045_8260) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber D25TL0M9GQ18 - Failed! - 409!
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:887, Name:FA_M8X7732) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber C17K5A0DDNCR - Failed! - 409!
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:998, Name:FA_M9X7860) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber C17KC3E4DNCR - Failed! - 409!
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:484, Name:fa004-p1) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber D25NR0RGF8J7 - Failed! - 409!
Full Response Data:
<?xml version="1.0" encoding="UTF-8"?><computer_group><id>165</id></computer_group>

Device with serialnumber QP052168DNR - OK! - 201
Full Response Data:
<?xml version="1.0" encoding="UTF-8"?><computer_group><id>165</id></computer_group>

Device with serialnumber C07M2A5DDWYL - OK! - 201
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:1204, Name:fa004-p6) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber D25TL0KSGQ18 - Failed! - 409!
Full Response Data:
<?xml version="1.0" encoding="UTF-8"?><computer_group><id>165</id></computer_group>

Device with serialnumber D25M40CTF8J8 - OK! - 201
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:456, Name:fa006-r1c1) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber D25NR0QYF8J7 - Failed! - 409!
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:464, Name:fa006-r1c2) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber D25NR0QCF8J7 - Failed! - 409!
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:784, Name:fa006-r2c1) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber D25NR0R8F8J7 - Failed! - 409!
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:783, Name:fa006-r2c2) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber D25NR0PEF8J7 - Failed! - 409!
Full Response Data:
<?xml version="1.0" encoding="UTF-8"?><computer_group><id>165</id></computer_group>

Device with serialnumber D25M40CWF8J8 - OK! - 201
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:471, Name:fa006-r2c4) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber D25NR0R2F8J7 - Failed! - 409!
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:457, Name:fa006-r2c5) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber D25NR0QTF8J7 - Failed! - 409!
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:462, Name:fa006-r2c5) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber D25NR0QQF8J7 - Failed! - 409!
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:459, Name:fa006-r3c1) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber D25NR0D9F8J7 - Failed! - 409!
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:460, Name:fa006-r3c2) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber D25NR0RCF8J7 - Failed! - 409!
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:461, Name:fa006-r3c3) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber D25NR0QGF8J7 - Failed! - 409!
Full Response Data:
<?xml version="1.0" encoding="UTF-8"?><computer_group><id>165</id></computer_group>

Device with serialnumber D25NR0REF8J7 - OK! - 201
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:463, Name:fa006-r4c1) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber D25NR0QWF8J7 - Failed! - 409!
Full Response Data:
<?xml version="1.0" encoding="UTF-8"?><computer_group><id>165</id></computer_group>

Device with serialnumber D25M40D2F8J8 - OK! - 201
Full Response Data:
<?xml version="1.0" encoding="UTF-8"?><computer_group><id>165</id></computer_group>

Device with serialnumber D25NR0R6F8J7 - OK! - 201
Full Response Data:
<?xml version="1.0" encoding="UTF-8"?><computer_group><id>165</id></computer_group>

Device with serialnumber D25NR0RDF8J7 - OK! - 201
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:468, Name:fa047-c1p2) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber D25NR0QDF8J7 - Failed! - 409!
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:479, Name:fa047-c1p3) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber D25NR0RHF8J7 - Failed! - 409!
Full Response Data:
<?xml version="1.0" encoding="UTF-8"?><computer_group><id>165</id></computer_group>

Device with serialnumber D25M40GGF8J8 - OK! - 201
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:478, Name:fa047-c2p1) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber D25NR0R1F8J7 - Failed! - 409!
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:495, Name:fa047-c2p2) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber D25NR0R4F8J7 - Failed! - 409!
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:475, Name:fa047-c2p3) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber D25NR0QJF8J7 - Failed! - 409!
Full Response Data:
<?xml version="1.0" encoding="UTF-8"?><computer_group><id>165</id></computer_group>

Device with serialnumber D25M40D1F8J8 - OK! - 201
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:469, Name:fa047-c3p1) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber D25NR0R7F8J7 - Failed! - 409!
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:470, Name:fa047-c3p2) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber D25NR0QPF8J7 - Failed! - 409!
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:473, Name:fa047-c3p3) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber D25NR0QEF8J7 - Failed! - 409!
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:786, Name:fa047-c3p4) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber D25NR0QNF8J7 - Failed! - 409!
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:481, Name:fa047-c4p1) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber D25NR0RAF8J7 - Failed! - 409!
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:482, Name:fa047-c4p2) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber D25NR0R5F8J7 - Failed! - 409!
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:472, Name:fa047-c4p3) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber D25NR0QVF8J7 - Failed! - 409!
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:477, Name:fa047-c4p4) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber D25NR0QLF8J7 - Failed! - 409!
Full Response Data:
<?xml version="1.0" encoding="UTF-8"?><computer_group><id>165</id></computer_group>

Device with serialnumber D25M40CYF8J8 - OK! - 201
Full Response Data:
<?xml version="1.0" encoding="UTF-8"?><computer_group><id>165</id></computer_group>

Device with serialnumber W89118060TG - OK! - 201
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:755, Name:FA112X8887MB) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber C1MM336BDV30 - Failed! - 409!
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:773, Name:fa119-Gillison) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber W80237HM5PC - Failed! - 409!
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:661, Name:FA123GDH) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber D25GH0XCDPNK - Failed! - 409!
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:936, Name:FA123GDH2) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber C02M42FMF6T6 - Failed! - 409!
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:483, Name:fa129-c3) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber D25NR0D3F8J7 - Failed! - 409!
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:753, Name:FAM11X8732HBL) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber D25QN0M8GG7D - Failed! - 409!
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:999, Name:FAM8X8731) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber C02KW52RDNCR - Failed! - 409!
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:872, Name:SH158B-iMac) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber QP0341CQDNN - Failed! - 409!
Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Computer (ID:1034, Name:SH161X7145) is not site-enabled for this site</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>


Device with serialnumber D25RK0W0GG7D - Failed! - 409!

**Comment by mike-levenick** [comment]
Hello, not sure why the account would get flagged, perhaps from the email signature stuff? 

Anyways, regarding the MUT issues, is there a chance that the static group you created was inside a Site in Jamf Pro? 

When you say you're not doing anything with sites, do you mean that you don't have them in Jamf Pro at all, or that you're not trying to change sites with this update run?
