### ISSUE TITLE
Asset Tag update causes program to crash

### ISSUE THREAD

**Issue by zee-merali** [mike-levenick/mut#14]
[CrashReport.txt](https://github.com/mike-levenick/mut/files/2255387/CrashReport.txt)

I tried updating the "asset tag" field for mobile devices using an administrator account (LDAP and standard) with simple passwords (as suggested on Jamf Nation) but Mut keeps crashing every time I attempt to run the update.  I tried to run the debugger, but since the program just quits, there's no output.  I am able to update all the other fields without a problem.
I've attached the crash report here.

**Comment by mike-levenick** [comment]
Sorry for the delayed response here. When you run the update, does it crash immediately? Or just partway through? Does it crash when you run the preflight check, or only when you actually hit submit? If you use the same CSV that you are using for Asset Tags, but simply change the dropdown to something else, does it still crash? As in, does it seem related to that CSV, or to that particular set of dropdowns?

**Comment by Mooler111** [comment]
Same happened to me. It was due to the spec chars that we used (i.e Ö,Ä,Å). After replacing those it worked a charm!

**Comment by zee-merali** [comment]
It doesn't crash immediately, but it never begins the update.  The status bar stays at 1 of x, and doesn't progress.  Mut then crashes and the update isn't run.  It's fine in the pre-flight, and is reading the columns correctly.
I use the same CSV for all the updates I do, and it works for Device Name, and for adding to Static Groups.

**Comment by hectorNISD** [comment]
I've had the same issue as zee-merali regarding the asset tags and the application quitting unexpectedly early in the morning. The MUT will update the asset tag very slowly and around half way application will quit unexpectedly. I opened a ticket with our Jamf pro mdm later that day. They were unable to provide any correlation. I tried the utility again during the day with the same delay but no application crash. 


[Archive.zip](https://github.com/mike-levenick/mut/files/2302784/Archive.zip)


![themuterror](https://user-images.githubusercontent.com/42544565/44344719-ff2bbf80-a456-11e8-9b8b-2ec30d2359d3.png)

**Comment by mike-levenick** [comment]
I have been trying to track down an issue that causes MUT to crash upon updating a slow server. It seems that if things get built up a bit, the Jamf Pro server throws some sort of response that MUT isn't expecting (or returns a null response is my suspicion) which is causing the error here.

This is actually the next thing that I'd like to fix. There are lots of checks on the CSV that gets uploaded, to try to avoid things like this on the preflight, but there is very little checking of the response returned by Jamf, and it just gets dumped out to the user, so if the response isn't what MUT is expecting (or is null) it could cause this.

The trouble is it's a bit difficult for me to replicate, so it's hard to troubleshoot and resolve. I'll keep digging in and see what I can discover.

**Comment by hectorNISD** [comment]
mike, You were correct about our Jamf Pro server. Thank you for your response. Are there any plans to add the ability to update multiple attributes for the same serial?

**Comment by mike-levenick** [comment]
> mike, You were correct about our Jamf Pro server. Thank you for your response. Are there any plans to add the ability to update multiple attributes for the same serial?

I recommend you check out the new Inventory Preload feature of Jamf Pro 10.8. It allows updates to multiple user fields at once with ease.
