### ISSUE TITLE
404 on Device but only when adding to static groups?

### ISSUE THREAD

**Issue by gforsyth4** [mike-levenick/mut#16]
I am testing adding an iOS Device to a Static Group in the JSS. I am using a serial identifier for the machine and got the group id from the URL per the instructions. Any ideas? The same serial identifier works when naming the device... ?

Device GCGV5G6JHLFD - Failed! - 404!

HTTP 404 means 'not found'. There is no device with serialnumber GCGV5G6JHLFD enrolled in Jamf Pro.

**Comment by mike-levenick** [comment]
This is an error in messaging. The 404 is related to there not being a
group with that ID yet.

Column A should be the serial and column B should be the ID of a static
group that exists already in Jamf.

I need to update the messaging on that 404 for groups.

**Comment by gforsyth4** [comment]
Awesome. Thanks for the reply and great work on MUT.

Appreciate all the work.

**Comment by mike-levenick** [comment]
Sure thing. It would be something like this. 
![image](https://user-images.githubusercontent.com/12515543/46804192-9ad6ff00-cd27-11e8-8776-14473207ee3f.png)
For this image, the group ID would be 9. So your CSV would be something like:
`SERIAL,GROUP ID`
`C11111,9`
`C11112,9`
`C11113,9`
`C11114,9`

Which would add those devices to that group. Use the following settings in MUT

![image](https://user-images.githubusercontent.com/12515543/46804404-1c2e9180-cd28-11e8-9b35-8116e1461869.png)

Make sure that you are on "mobile devices" if you're trying to add mobile devices to the group, and vice versa for computers, and make sure that the static group that you're trying to create exists in the proper area of Jamf (don't try adding mobile devices to a computer static group, etc.). Those things seem silly, but I find it happens fairly often, which I think is a sign that perhaps the MUT UX could use some clarification. 

If that still doesn't work, try turning on advanced debugging, and paste part of the output here--including the top section with the "pre flight check" and such.

**Comment by gforsyth4** [comment]
I am good! Thanks so much!
