### ISSUE TITLE
Feature Request - Dark Mode support

### ISSUE THREAD

**Issue by richeames** [mike-levenick/mut#19]
Love your app and been using it since it was first released.

Any chance you can add dark mode support, I thought I had a problem with the app until I realized that with dark mode enabled on my computer  I couldn't see any of the fields when The MUT opens. Right now I'm using Night Owl so I can see the fields of any app that doesn't support or look great in dark mode.

Dark and light mode comparison.
![Screen Shot 2019-05-01 at 10 45 42 AM](https://user-images.githubusercontent.com/11298391/57022888-8d6b5e80-6bfe-11e9-8184-5ac5d1f58215.png)

Thanks !

**Comment by mike-levenick** [comment]
Sorry for the delayed response here, this was resolved in 4.3.0

https://github.com/mike-levenick/mut/releases/tag/v4.3.0

https://github.com/mike-levenick/mut/commit/6152e0cbc9fe4368cbcbb5b8fd7032b13671c9f3
