### ISSUE TITLE
Error 400!

### ISSUE THREAD

**Issue by rspetman** [mike-levenick/mut#2]
Can you explain what error 400! is please?

**Comment by mike-levenick** [comment]
Hello, the error codes which are displayed are HTTP error codes. HTTP error code 400 is "bad request" and is usually something to do with malformed XML being submitted, or trying to submit the wrong thing to the wrong place.

If you'd like, you can turn on advanced debugging under the settings menu at the top of the screen, then do the update run again, and then paste part of the contents of the log box here and I'll take a look.

**Comment by rspetman** [comment]
This is what I get

Full Response Data:
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Bad Request</p>
<p>Unable to match mobile_device </p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.1">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>

**Comment by mike-levenick** [comment]
Interesting, can you please paste the whole top of the output, the part that gets generated like when you run the pre-flight check?

**Comment by rspetman** [comment]
CSV: /Users/rachel/Downloads/NSA Device Name.csv
Found 65 rows in the CSV.

Example row from your CSV:
SerialNumber: DN6HRNN3DFHW, Device Name: NSA.IML01.02

==================================================
Please review the above information. If everything looks good, press the submit button. Otherwise, please verify the dropdowns and your CSV file and run another pre-flight check.
==================================================

**Comment by rspetman** [comment]
I've done this successfully over 15 times now, and suddenly two batches are failing. I confirmed the SN's are in jamf.

**Comment by mike-levenick** [comment]
I see. Can you re-create consistently, and is it always the same devices failing? Are other devices working successfully?

Are the devices showing up as managed and supervised in the JSS? Can you send other MDM commands to them such as inventory updates? 

One other thing to try would be to do a "clear defaults" from the settings menu at the top, then close the app, restart it, set everything up, turn on advanced debugging, and run another update, and then paste the whole output if you don't mind (from Welcome to MUT! all the way down through some of the failures, for all the info spit out up at the top).

**Comment by rspetman** [comment]
Yes, we have two groups of iPads consistently failing. I can continue to successfully update others. They ARE managed and supervised in jamf. I'll try what you suggested and will post an update shortly.

**Comment by rspetman** [comment]
Clearing the defaults worked!! Thanks so much :)

**Comment by mike-levenick** [comment]
Excellent! Glad to hear it. That's very strange, not sure what the problem could have been. Just glad it's working!

**Comment by itdir** [comment]
Hi Mike,

I'm having this issue too, but clearing the stored settings (menu text has changed) and reopening the app didn't work.  The CSV was exported from JSS, so the S/Ns came directly from there.

Any other suggestions?

Thanks!
Brian

**Comment by mike-levenick** [comment]
@itdir What version of MUT are you using? Can you enable "advanced debugging" from the menu at the top, and then send over the full output (including the text from the pre-flight check at the top) ?

**Comment by mike-levenick** [comment]
Brian,

Sounds good. I'll just consider it resolved then, no need for the output. 4.1 handles most formats well I thought, including UTF8 from excel, but I'll check into numbers.app and UTF8. 

Obligatory XKCD

![image](https://user-images.githubusercontent.com/12515543/43337266-f4ab201c-9198-11e8-80ec-633deff95695.png)

**Comment by itdir** [comment]
Ya, I ran 177 updates and only 8 failed, so I don't think it has anything to with the app.  Again, thanks for the time and effort!

**Comment by TryPad** [comment]
Hello,
could you please help me find a solution to my problem? I tried to update the Device Name thru the Serial Number, but I got the 400 error! "Device is not site-enabled for this user"
Thanks!
Cyrille

**Comment by mike-levenick** [comment]
@TryPad I'm guessing perhaps your user has site permissions, and perhaps you do not have permissions to send commands to ipads in the site where that one exists?

**Comment by TryPad** [comment]
Thanks for your quick answer! Associating Serial Number to Username or username to Static group is working... Would there be a special site permission for SN -> DN?

**Comment by TryPad** [comment]
Hi Mike!
I asked about the Jamf user used to run MUT... It has actually "full access to the organization"... Winter's coming, a deep rabbit hole too then ;-(
Cyrille, ready for some more amazing magic from your part!

**Comment by TryPad** [comment]
Hi Mike!
Since the user I logged in with to run MUT has full access to the organization, do you advise me to give up and go for a manual name modification?
Thanks for your wise experience!
Cyrille
