### ISSUE TITLE
Will the MUT work with Jamf School?

### ISSUE THREAD

**Issue by BeccaShafer** [mike-levenick/mut#23]
Considering moving from Jamf Pro to Jamf School.  Will the MUT still work?

**Comment by mike-levenick** [comment]
Hi Becca,

I hope you're doing well! Unfortunately, as of right now, The MUT is for Jamf Pro only. 

I just reached out to a Jamf School developer, and got some information on their API documentation. The API looks robust and awesome, but it would be a while before MUT (or any similar tool) could be developed to work with Jamf School.

**Comment by cakmak23** [comment]
is there any progression the development to MUT for Jamf School?
