### ISSUE TITLE
How to do (Extension)

### ISSUE THREAD

**Issue by Luctinseau** [mike-levenick/mut#30]
I would like to assign extension attributes based on the serial number of the ipad; I don’t see how the CSV file was built, I understood that the attributes were defined by an ID but how to assign the ID and its content?

**Comment by mike-levenick** [comment]
Your CSV should have serial numbers in column A, and the value to go in the Extension Attribute in column B. 

There is a box in the MUT GUI for “EA ID”, which is where you put the ID of the extension attribute. 

From there, just make sure your drop downs are on mobile devices and extension attributes.

**Comment by mike-levenick** [comment]
The Extension Attribute ID can be found in the URL bar of your browser while you're looking at the EA in Jamf Pro GUI. You'll find in the URL something along the lines of "id=##". For example, this would be EA with an ID of 2:

<img width="511" alt="Screen Shot 2019-07-11 at 7 21 53 AM" src="https://user-images.githubusercontent.com/12515543/61050443-a20d6500-a3ac-11e9-9782-5bff42f4236d.png">

So we would set up the MUT gui like this to update the extension attribute with ID 2 (my dropdown is technically incorrect here, as I'm showing a computer EA, but you get the idea):

<img width="465" alt="Screen Shot 2019-07-11 at 7 23 01 AM" src="https://user-images.githubusercontent.com/12515543/61050521-cbc68c00-a3ac-11e9-82e7-a99c0c0437c4.png">

Example CSV:

<img width="379" alt="Screen Shot 2019-07-11 at 7 18 08 AM" src="https://user-images.githubusercontent.com/12515543/61050342-6ecad600-a3ac-11e9-9615-aa266ab08e65.png">
