### ISSUE TITLE
MUT v5 crashing when updating usernames with whitespace

### ISSUE THREAD

**Issue by ahousseini** [mike-levenick/mut#34]
Tried to update usernames with whitespace and MUT.app crashed. The MUT.app v4 can handle usernames with whitespace.

**Comment by mike-levenick** [comment]
@ahousseini do you mind providing a bit more information about what you're trying to do, and what configuration you have when things crash?

- What version are you on?
- A screenshot of MUT prior to hitting "submit"
- A copy of your CSV -- or a sanitized one with similar information that also causes things to crash

The following line is the one that should allow your URL to have spaces in it: 

`encodedURL = NSURL(string: "\(cleanURL)".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)! as URL`

I am discovering that I'm double-encoding spaces, so they get converted from " " to "%20", but then the % gets encoded to "%25", so we get "%2520". I'll work on that. That said, it shouldn't be crashing--and it isn't for me.

**Comment by mike-levenick** [comment]
@ahousseini I resolved the double-encode issue in 5.0.4b1, you can download it here to test: https://github.com/mike-levenick/mut/releases/tag/v5.0.4b1

If that does not solve your issue, please provide the information requested above, and I'll try to recreate and get this fixed for you ASAP.

**Comment by jedetaste** [comment]
@mike-levenick Still the same. I attached a screenshot. At the serial numbers you can see that there is something wrong reading the CSV. When I delete the username column the CSV is working fine. When I copy the exact same username column and using it in MUT v4 everything works. I used your beta 5.0.4b1 and the 5.0.4 release.
<img width="662" alt="Screenshot 2019-08-08 at 16 10 50" src="https://user-images.githubusercontent.com/23168512/62710400-8622d080-b9f7-11e9-92d4-ecff9a88777f.png">

**Comment by ahousseini** [comment]
@mike-levenick Still the same. I attached a screenshot. At the serial numbers you can see that there is something wrong reading the CSV. When I delete the username column the CSV is working fine. When I copy the exact same username column and using it in MUT v4 everything works. I used your beta 5.0.4b1 and the 5.0.4 release.
<img width="662" alt="Screenshot 2019-08-08 at 16 10 50" src="https://user-images.githubusercontent.com/600317/62710638-e7e33a80-b9f7-11e9-8c1c-d4df66e30faf.png">

**Comment by mike-levenick** [comment]
@ahousseini it looks like it's seeing a line break in that column for some reason. 

Do you have non-english characters in any of your usernames? I had a different user report similar behavior when they had an ñ in their department (Español). It ended up being a goofy issue with how Excel was saving their spreadsheet. If you cat the file out in terminal, what does it return?

The fix for them was to re-open Excel and then re-save the CSV as "CSV UTF-8" which fixed the issue:

![image](https://user-images.githubusercontent.com/12515543/62710831-a2098080-b9bd-11e9-98a5-b81f985a765b.png)

**Comment by mike-levenick** [comment]
Curious if the CSV UTF-8 resolved the issue for you. Let me know either way!

**Comment by ahousseini** [comment]
It works now, when saving the CSV as UTF-8. Thank you!

**Comment by keithemyers** [comment]
> @ahousseini it looks like it's seeing a line break in that column for some reason.
> 
> Do you have non-english characters in any of your usernames? I had a different user report similar behavior when they had an ñ in their department (Español). It ended up being a goofy issue with how Excel was saving their spreadsheet. If you cat the file out in terminal, what does it return?
> 
> The fix for them was to re-open Excel and then re-save the CSV as "CSV UTF-8" which fixed the issue:
> 
> ![image](https://user-images.githubusercontent.com/12515543/62710831-a2098080-b9bd-11e9-98a5-b81f985a765b.png)

That worked, thanks!!
