### ISSUE TITLE
Can't Add to Static Group if source file has unknown serials

### ISSUE THREAD

**Issue by JCSmillie** [mike-levenick/mut#35]
We are in the process of migrating to another JAMF Server.  Up until the v5 release I used to export all serials from the new server and use MUT to import them into a "Delete Me" static group on the old server so I knew what records could be removed thus leaving me with a list of what hardware still needs attention.  This worked before August.  When you hit an error it just kept chugging along, but now when you hit the first computer that doesn't match MUT errors out and doesn't continue.  Is this expected behavior now?  It wasn't before.

I am using the template.  Simply a list of serials, choose "Computer Static Group", choose to add or replace (Doesn't matter), click prefilght and then UPDATE.  Errors out immediately with "Error: Unable to match computer "

Thoughts?

**Comment by mike-levenick** [comment]
Hello.

This is a hinderance of the API, and a bit of a mixed blessing with MUT v5.

Basically MUT v5 does group updates in one big API call, which is _vastly_ more efficient than v4. If you wanted to add 2000 devices to a group, v4 makes 2000 API calls. v5 makes 1 call.

There is a feature of the API where if one of the devices is not found in Jamf, the entire api call fails. 

As a workaround for now, head to the app store and download the "MUT Classic" and use that to make your group updates. I think as a feature request for the future, we may add an ability to make those group updates "inefficient", and do a per-line API call, which will be functionally identical to v4, but for now, I would say, just use MUT Classic.

**Comment by JCSmillie** [comment]
That worked, thank you!

**Comment by mike-levenick** [comment]
Awesome! Glad to hear it!
