### ISSUE TITLE
EAs not getting set

### ISSUE THREAD

**Issue by wcwelch** [mike-levenick/mut#38]
About a week ago, I used version 5.0.5 to set values for a number of EAs. I am starting to hear from end user that there devices are not grouped. When looking into it, it appears that the EA values were not set. I went back and looked at mut.log and it's not showing any errors for the SNs I look up.

In one "batch" in particular, out of 550 devices, 6 were not set. For this batch of iPads, I was only setting one EA to "2026".

 I know this isn't much to go on, but it's all I have.

**Comment by mike-levenick** [comment]
Interesting. Can you please try trimming down the CSV file to just the devices that didn't work (or at least a couple of them) and try again, to see if the behavior persists?

**Comment by wcwelch** [comment]
Looks like this is a bug within the JSS, not the MUT.

**Comment by wcwelch** [comment]
Bug is PI-007467. When a device checks into JAMF via Self-service, a "timing issue" can occur. When this happens all EAs for that device are erased causing the iPad to lose all apps and restrictions.

**Comment by mike-levenick** [comment]
@wcwelch Glad to hear it was not a MUT issue. Let us know if there's anything else we can do to help!
