### ISSUE TITLE
MUT v.5 crashing when trying to open CSV

### ISSUE THREAD

**Issue by jaellington** [mike-levenick/mut#39]
Hi Mike,

I'm experiencing an issue where the MUT crashes when I browse for and attempt to open a CSV file.  I've been using MUT for a couple of months, and it has been a lifesaver.  This issue just cropped up today.
As far as I can tell, my CSV is formatted correctly.  The message I get is that 'MUT quit unexpectedly.'  Do you have any idea what would cause that?

**Comment by mike-levenick** [comment]
Any chance you have international characters in your sheet? Such as ñ? If so, be sure to export the csv as UTF-8 format from excel.
