### ISSUE TITLE
User updates

### ISSUE THREAD

**Issue by pdhowell** [mike-levenick/mut#4]
I have a CSV that I am trying to update several fields including some EA but no matter which Attribute I choose to update, it returns with **Device with name Username - Failed - 404!**. 

> CSV: /Users/pdhowell/Desktop/MUT CSVs/AdobeAccessGroup-JSSMUT.csv
> Found 2 rows in the CSV.
> 
> Example row from your CSV:
> Username: gpcalhoun, User's Site by ID: 5
> 
> Device Type: Users
> ID Type: Username
> Attribute Type: User's Site by ID
> 
> Beginning Update Run!
> 
> Device with name Username - Failed! - 404!
> 
> HTTP 404 means 'not found'. There is no device with name Username enrolled in your JSS.
> 
> Device with name gpcalhoun - OK! - 201

**Comment by mike-levenick** [comment]
So, it looks like that is just a failure in trying to run the first line of your CSV, which is the header.

It is trying to update the username "Username", which doesn't exist. The MUT will run the first row of your CSV, even if it's just headers. It will throw a 404, but then just move on and update the next row.

I believe there is an issue with updating user extension attributes via the API at this time. I can do some testing to confirm, but I know it was there a couple JSS versions ago. Other attributes such as asset tag should work just fine tho.

**Comment by pdhowell** [comment]
When I run it the update it’ll say it completed but the changes aren’t there. Do you have new help me for the current version? The video is out of date.

Thank you,

Parker Howell
Level II District Technician | Prosper ISD
(T) 469-219-2150<tel:469-219-2150> Extension 14162
(Direct) 469-219-2086

**Comment by mike-levenick** [comment]
Understood. Have you tried updating something other than extension attribute? Do those update successfully?
