### ISSUE TITLE
adding EA_

### ISSUE THREAD

**Issue by JD2009CK** [mike-levenick/mut#40]
Hello,
I tried adding 2 new Values adding the EA_# and when I do a preflight check it shows the values but it does not give me the option to submit.

Thank you.
JD

**Comment by mike-levenick** [comment]
Hello @JD2009CK I apologize for my (extremely) delayed response on this. Did you ever get this issue sorted out? If not, can you please send me a copy of your CSV, and a screenshot of what you see in the GUI?
