### ISSUE TITLE
2 Factor enabled JAMF issue

### ISSUE THREAD

**Issue by scottlnrd** [mike-levenick/mut#47]
Testing the tool for the first time, I tried and succeeded in updating 205 records in JAMF. However, because of the two-factor auth, I had 205 DUO prompts for authorization. Not sure if there's any way around this.

**Comment by mike-levenick** [comment]
Interesting, I can't say as I've ever seen that. 

What version of MUT were you using? Also, is this perhaps an LDAP user and your DUO setup is through LDAP? If you try creating a new local user for Jamf Pro, and using that, do you see the same behavior?

**Comment by scottlnrd** [comment]
I believe its 5.2 I was using. And I think our auth is through active directory with DUO.

**Comment by mike-levenick** [comment]
Understood. Yeah, I am guessing that prompt came from AD. Perhaps try creating an API user in Jamf Pro, and see if you see the same behavior. This will also allow you to be granular with the permissions you want for that API user, and to turn it on/off as you see fit for additional security.

**Comment by scottlnrd** [comment]
Thanks. I'll see what's possible there.
