### ISSUE TITLE
Mobile device name resets after next inventory update

### ISSUE THREAD

**Issue by b600596** [mike-levenick/mut#48]
Hi Mike,

first at all, thank you for this great tool :-)
Since Jamf 10.25.x we got the problem that device names set by the MUT are reset to default values after inventory update.
Device names set by hand persists after inventory update.
Extension attributes set by the MUT also persists after inventory update.
I tried to set the device name by the MUT classic and the MUT V5 with the same result.
In Jamf 10.24.x all works fine.

Hope you have any idea what we could do.

**Comment by robotech99** [comment]
We are on Jamf Pro 10.26 with MUT 5.3.2 and noticed the following. When changing mobile device names the "Enforce Mobile Device Name" box is no longer getting checked in the device record. So after a batch rename the end user can change the device name, after next inventory the name in Jamf Pro will also change. Is this due to changes in Jamf Pro 10.25+ or the latest version of MUT?

**Comment by mike-levenick** [comment]
Hello. Can you please post a copy of the MUT.log?

The way this works is that MUT changes the name, and then generates a mobile device command to update the name. This mobile device command is what actually enforces the name. I'd be curious if MUT is throwing an error when attempting to set that name.

I'd also be curious if you see the "DeviceName" command generated in Jamf Pro, and if so, if the jamfproserver.log has anything to say about that command and its outcome.

**Comment by mike-levenick** [comment]
Hello again. @b600596 and @robotech99 this is a known issue in Jamf Pro, and has been filed as PI-009042. I recommend you reach out to Jamf Support to have a case created, to get your information tied to this PI and help get it resolved as quickly as possible.

**Comment by mike-levenick** [comment]
@b600596 @robotech99 

I think you'll be excited to know I just released MUT v6, has a fix for this issue. Check it out, and let me know how it works! https://github.com/mike-levenick/mut/releases/tag/v6.0.0 

As always with MUT, I strongly recommend trying out a small, test run of just a few devices before doing a massive update to your entire fleet. MUT is a very powerful tool, and while I've done plenty of testing, it is good to be careful, especially with a change as massive as this.
