### ISSUE TITLE
Trying to update Mobile Device Name for an IOS device

### ISSUE THREAD

**Issue by motnoslo** [mike-levenick/mut#5]
Is the Mobile Device Name the "general" section of the device inventory, the same as the "Device Name"  in the "attribute to update" dropdown in The MUT?

I tried to update the Mobile Device name from iPad to a actual name. The MUT seems to be ok with it, but afterwards the Mobile Device name is still iPad. First time I'm using the Mut, so I assume I'm doing stupid, unless the device name and mobile device name are different. I'm saving as a Windows .csv too.
Any ideas?

**Comment by mike-levenick** [comment]
Hello,

The only way to update Device Name for iPads in the JDS is via the "enforce mobile device name" checkbox in the JSS.

What the MUT does, is it generates an MDM command, which will then tell the device to change the name.

In order for this to work, you have to have a supervised device, the device has to have MDM communication, and it has to be turned on and on network. 

You can check in the management tab for the device, and see if it has a pending "Set Device Name" command. 

If you got a 201 - success, it sounds like the command was likely generated correctly, and the name may just update the next time the device talks to the JSS.

**Comment by motnoslo** [comment]
Hmmmm, seems like it might be a JAMF issue. I have the "enforce mobile device name" checked. It is a supervised device, it is communicating. When I went into the "edit general" section, I can change the name to Mickey Mouse, hit save. I go back out it still shows iPad, edit General, it shows Mickey Mouse, hit save. I close the device page, search for the device again, "edit general", it's back to iPad.

**Comment by mike-levenick** [comment]
Do you have a configuration profile scoped to that device to block changing device name via the restrictions payload? 

That will stop even admins from changing the name, and if you have that set up, it will behave similarly to what you're describing.

**Comment by motnoslo** [comment]
Nope. Just check the config profile, no block on changing the name.

**Comment by mike-levenick** [comment]
Curiouser and curiouser. 

If you go to the inventory record for the device and go to the management tab, does it have a pending Set Device Name command? If you go to the history tab for management history, did that command ever go through? Is it being generated and failing? Being generated and succeeding but then flipping back? Not being generated at all?

**Comment by motnoslo** [comment]
Hi Mike,

My apologies for disappearing, but as school approaches I'm fighting many
fires.
I went ahead and ran a .csv file with about 75 devices to change the device
name, MUT was had a mix of OK's and Failed, but on the devices that I was
looking at the time, the device name was changed. I need to check the
serial for a failed device and see if its device name has changed. Does the
device have to be on to come back with an OK? Not all the devices were on
at that time.

**Comment by mike-levenick** [comment]
Sounds good. What is the error number on the failures? Is it 404 or something else? 

Make sure you have MDM communication to a supervised device, which is turned on and on-network, and you do not have a config profile scoped to the device which restricts name changes. 

Other than that, depending on what the error number is, we can do other troubleshooting steps. You can also enable Advanced Debugging from the menu bar.

**Comment by motnoslo** [comment]
I checked two of the many devices that had failed, but they we not on at
the time I ran MUT. It makes sense that they failed at runtime, but when I
turned them on the device name had changed. The fails were 400's.
I think we're good.
Thanks again!

**Comment by mike-levenick** [comment]
Sounds great. I'll close 'er up.
