### ISSUE TITLE
Deleting from PreStage Enrollment Failing

### ISSUE THREAD

**Issue by stephanpeterson** [mike-levenick/mut#52]
I'm trying to delete Macs from a PreStage Enrollment group but am being told the group ID doesn't exist:

2020-12-21 10:32:32 [INFO  ]: Updating the current prestage scope at https://host.myorg.com:8443/uapi/v2/computer-prestages/2/scope/delete-multiple
2020-12-21 10:32:32 [ERROR ]: Failed scope update. 404.
2020-12-21 10:32:32 [ERROR ]: {
  "httpStatus" : 404,
  "errors" : [ {
    "code" : "INVALID_ID",
    "description" : "Computer Prestage with id 2 does not exist",
    "id" : "2",
    "field" : "id"
  } ]
}

Yet, here's the URL:

https://host.myorg.com:8443/computerEnrollmentPrestage.html?id=2&o=r

This is an on-prem instance running v10.26 and I'm using my account which has full rights.

Further, I'm running 5.3.2 of MUT.

**Comment by mike-levenick** [comment]
Hey Stephan,

This is actually a Jamf Pro product issue related to how the UAPI handles requests from users with LDAP group permissions.

Making a new, local, admin user in Jamf Pro, and using that instead, should resolve the issue for you. :)

**Comment by mike-levenick** [comment]
Spoke with Stephan via slack and confirmed local user resolved issue.
