### ISSUE TITLE
Adding departments and/or buildings to Jamf pro cloud

### ISSUE THREAD

**Issue by grainofric3** [mike-levenick/mut#54]
Im having difficulty finding the right options to do this, or maybe its not a supported option, but essentially, I would like to import a CSV list of departments and buildings into JSS en masse
![Screen Shot 2021-01-08 at 3 51 53 PM](https://user-images.githubusercontent.com/59681626/104072814-6fbf0c80-51c9-11eb-9e72-0da2159de49c.png)

**Comment by mike-levenick** [comment]
Hello @grainofric3 , unfortunately MUT will not create these on-demand. MUT actually doesn't create users either--that's a Jamf Pro feature that MUT happens to be able to leverage--if a device is assigned to a User and that User does not exist yet, Jamf Pro creates it.

I know there are plenty of bash scripts and things like that out there, which can create Buildings/Departments en masse, but MUT is not able to do it. 

I recommend you reach out to Jamf Support to see if they have any scripts for you, and if they're not able to find one, I may be able to dig one up somewhere.

**Comment by grainofric3** [comment]
understood, thanks Mike, if you happen to come across any scripts lmk, but ill keep digging to see.
