### ISSUE TITLE
Updating Static Group

### ISSUE THREAD

**Issue by rpetitto** [mike-levenick/mut#6]
Serial Numbers confirmed, Static Group created, pulled uuid from USL

When running MUT, get 404 errors stating that Serial#s don't exist.

**Comment by mike-levenick** [comment]
If you wouldn't mind, paste the entire output (you can cut off everything below the first few run lines, but include the top bit with the preflight check results etc)

**Comment by mike-levenick** [comment]
Just wanted to follow up--still an issue?
