### ISSUE TITLE
MUT wants new templates

### ISSUE THREAD

**Issue by imcluis** [mike-levenick/mut#61]
I saw yesterday that there was an update to MUT in the Mac App Store - so i ran it.  I am instantly frustrated and really wish I would have not updated.  It is repeatedly asking me to use the "new " templates, SO I complied and downloaded the new ones via the link on the splash page.  I put the data from my old one (I cannot see a difference) and plugged it in.  I am STILL getting the attached message.  I LOVE the MUT.  BUT it has been the worst year in my 20 years of educational technology this year everything is going wonkers.  I cannot do my job inside of JAMF without this tool, there is no other tool that does this. I need to mass update iPad names (I've been trying for over a month, got that issue figured out with JAMF and now MUT wont work.  I am hoping this is is something simple. 

Thank you in advance
Christina
<img width="568" alt="Screen Shot 2021-04-16 at 1 14 54 PM" src="https://user-images.githubusercontent.com/82673709/115079240-bea9cb80-9eb5-11eb-8232-dcfb0d73c0b2.png">

**Comment by mike-levenick** [comment]
Hey Christina,

Sorry about the issues you're having. As of 5.4.1, the new templates should have "AppleCare ID" towards the end of them--if you're not seeing that, then perhaps the templates are not downloading correctly for you. I just double checked and they seem to be populating in the way I expect, but that doesn't necessarily help you.

As a solution, you can either modify the template/spreadsheet manually to include a column called "AppleCare ID" between "Lease Expires" and "Site (ID or Name)"

Or you can download the working mobile device template here: https://www.dropbox.com/s/au4jko29peivwag/MobileDeviceTemplate.csv?dl=0

Or you can simply download the previous version of MUT from GitHub releases here: https://github.com/mike-levenick/mut/releases/tag/v5.3.2
(Direct link to .dmg download: https://github.com/mike-levenick/mut/releases/download/v5.3.2/TheMUT_5_3_2.dmg )

Hope one of these works for you.

**Comment by imcluis** [comment]
Great! THank you I will download them from your link and give it a try.  Thank you so much for your quick response!
My Best to you, 
Christina Luis
Technology Support Specialist
Ed Services, ext. 2643
***@***.***

**Comment by mike-levenick** [comment]
@imcluis did that work for you?

**Comment by imcluis** [comment]
I have nto had the opportunity to try yet.  I have a small window to do renaming due to distance learning.  I will try to today and let you know.  I think the template was the issue. 
My Best to you, 
Christina Luis
Technology Support Specialist
Ed Services, ext. 2643
***@***.***

**Comment by imcluis** [comment]
Hi Mike, 
Just wanted to let you know the new copy of the template worked! Thank you!
My Best to you, 
Christina Luis
Technology Support Specialist
Ed Services, ext. 2643
***@***.***
