### ISSUE TITLE
MUT isn't working at all

### ISSUE THREAD

**Issue by imcluis** [mike-levenick/mut#68]
Hello, 
I used MUT last week just fine.  I am using the correct template- and the latest version. 
I have filled in the spreadsheet with the correct information (i've done this a million times). 
I am getting this error when trying to create new users and add users to devices. 
The template is the mobile device template (has the apple care on it) - serial#, Asset tag, user, real name, email address, position, department, room number, site, and extension attribute.  I removed my server and put myserveraddress.com (but the actual code has my url)

MUT goes super fast and gives me this error in the logs:
2021-09-21 02:53:14 [INFO  ]: Submitting a PUT to https://Myserveraddress.com/SSResource/mobiledevices/serialnumber/DMPS4CYEG5VW
2021-09-21 02:53:14 [ERROR ]: Failed PUT. 409.
2021-09-21 02:53:14 [ERROR ]: <html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Error: Problem with site name</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>

Please help. 
Thank you 
Christina

**Comment by mike-levenick** [comment]
Hi Christina, it seems to be upset about the name of the site that you’re
trying to add devices to. Can you post a screenshot of what MUT looks like
after the pre flight check?

**Comment by imcluis** [comment]
HI Mike, 
I removed the site name and now it is working! THank you for your quick response, by site I thought it meant URL site.

**Comment by mike-levenick** [comment]
Yep! Site ID/Name in the template.

By preflight check I mean the page that is shown after you upload your
template, but before hitting “Submit”—what does that page show?

**Comment by mike-levenick** [comment]
Ah yes. I believe it has an issue with the “Neutra Elementary”. Do you have
a Site with that exact name verbatim?

Otherwise, you can try with the site ID instead. If you go into Jamf Pro in
settings and go to sites and click that site you should see the site ID in
your URL.

If you have a site with that name, and name fails but ID works it’s
possible there’s an API issue.

**Comment by imcluis** [comment]
Hi Mike, 
Yes I do, I copied and pasted it so I didn’t spell it wrong.  Its ok I worked around it - I removed it from the spreadsheet and then did a mass update for that group of iPads.  Much less work than creating everything by hand.  Thank you for your quick response and help.  Also for a great app!

My Best to you, 
Christina Luis
Technology Support Specialist
Ed Services, ext. 2643
***@***.***
