### ISSUE TITLE
Crashing w/ large files

### ISSUE THREAD

**Issue by tryckman** [mike-levenick/mut#7]
Hi,

Thanks for creating such a great tool! The app seems to crash every time I use a csv with more than 3000 lines. Is this a known limitation? I have attached the crash log.
[MUT Crash Log.txt](https://github.com/mike-levenick/mut/files/1265313/MUT.Crash.Log.txt)

**Comment by mike-levenick** [comment]
Thanks for the heads up, I'll definitely do some testing. 

MUT stands for Mass Update Tool, not Moderately-Large Update Tool, a hard cap at 3000 is certainly not awesome. 

Does it crash immediately when you hit go, or after it reaches like 3000 in the run?

What endpoint, or is it all endpoints?
