### ISSUE TITLE
Enforcing names not working in MUT 6.0.0 / Jamf Pro 10.33

### ISSUE THREAD

**Issue by daledaleda** [mike-levenick/mut#74]
Very excited for the ability to change "Enforce Name" in MUT 6 — thanks to everyone volunteering on this project.

Unfortunately, I have tried it a few times, and it doesn't seem to be working for me. I've double-checked my CSV, and in the preview either TRUE or FALSE is showing up in "Enforce Name," but when I go into Jamf nothing is changed.

The biggest clue might be in the log — I see this for every PUT:

"[ERROR ]: Enforcing Mobile Device Names requires Jamf Pro 10.33 or higher. Please upgrade to the latest version of Jamf Pro in order to use this feature."

I am on 10.33.0-t1633712823, so I suspect the issue is it isn't correctly recognizing/parsing my version number? But that's just a theory.

Let me know if you need any more information from me or if I can run any tests on my end. Cheers!

**Comment by mike-levenick** [comment]
Interesting. Any chance your user has limited privileges? MUT uses an API
call to determine jamf pro version, and if that fails I bet it won’t update
names.

Try a new user with full admin privs to all sites and see if it helps. If
it does not, I will build out a version of MUT with a few extra log
functions so we can see what’s going on.

**Comment by daledaleda** [comment]
It did work with the new user — Jamf changes went through, no error in the log. Both users seem to have the same permissions (Standard User/Full Access/Administrator with everything checked), but obviously there's something different between the two to have two different outcomes.

Thanks!

**Comment by mike-levenick** [comment]
Interesting. I’m glad that fixed it! Pro is notoriously fussy about
permissions with the API, and new permissions that are added are not
automatically granted to users with custom privilege sets (which is a good
thing, but can lead to situations like this).

I would say if the drop down is definitely set to “admin” and not “custom”
on the non-working user, perhaps try flipping it to enroll only, then
saving, and back to full admin and saving again? Maybe something stuck
weird in the database.

Either way, I’m glad it worked! I’ll look at putting more verbose messaging
in place for situations like this.
