### ISSUE TITLE
Updating Static Group

### ISSUE THREAD

**Issue by gernb014** [mike-levenick/mut#8]
Greetings Mike- I am getting the issue with the other guy that never got back to you. Serial numbers for sure are correct. For the ID after creating the group I went to view and copied the uuid
![screen shot 2017-09-28 at 10 58 36 am](https://user-images.githubusercontent.com/30417742/30977094-285d524a-a43c-11e7-8c70-13c4772aebef.png)
Just starting with a small tester with 3 devices. Here's the output:
![screen shot 2017-09-28 at 10 58 05 am](https://user-images.githubusercontent.com/30417742/30977136-49acb9d6-a43c-11e7-89b8-d14304abed31.png)
![screen shot 2017-09-28 at 10 58 16 am](https://user-images.githubusercontent.com/30417742/30977140-4c2754b4-a43c-11e7-952c-dc941a0ddbe3.png)

I know serial numbers, and Static Group is made (might not be grabbing correct ID? I notice it changes when I reopen in different window), file is in a Windows Comma, and using full access admin

**Comment by mike-levenick** [comment]
Interesting, I wonder if it's an issue with the group ID and not actually the serial. If you turn on advanced debugging under the Settings menu at the top, what do you see?

The ID you should be grabbing will come after ?id= followed by a relatively short numeric number, which increments with every new group you create. This is in the URL immediately after going to a static group (not necessarily "view"ing the contents of it. just go to Static Mobile Device Groups > Click your group > go to URL)

Example:

![screen shot 2017-09-28 at 11 13 43 am](https://user-images.githubusercontent.com/12515543/30977803-52b1b3ae-a43e-11e7-9282-81a97378772a.png)

**Comment by gernb014** [comment]
Open and shut case. That was the problem. I was going Static Mobile->Open Group->View then grabbing from the URL. Instead just Static Mobile->Open Group grab from URL. Thank you very much. 

The only thing that kinda threw me was 
![screen shot 2017-09-28 at 11 24 17 am](https://user-images.githubusercontent.com/30417742/30978255-9ea079ac-a43f-11e7-978c-ac7a3001e8e4.png)
Literally the word viewing. Classic case of user error. Thank you for your quick help and response. Great product. I hope you are making some moolah off of this somehow

**Comment by mike-levenick** [comment]
It may be a case of user error, but it's also a case of poor documentation. I'll get the verbiage in the message updated, that's great feedback.

Thanks!

**Comment by itdir** [comment]
Hi Mike,

I know this is a closed issue, but I also am getting an error that the device serial number is not found when in fact it is correct.  Is this an issue of the error message not matching the actual problem.

> 
> Device (valid_serial_number) - Failed! - 404!
> 
> HTTP 404 means 'not found'. There is no device with serialnumber (valid_serial_number) enrolled in Jamf Pro.
> 
> Full Response Data:
> <html>
> <head>
>    <title>Status page</title>
> </head>
> <body style="font-family: sans-serif;">
> <p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Not Found</p>
> <p>The server has not found anything matching the request URI</p>
> <p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.5">here</a>.<br>
> Please continue your visit at our <a href="/">home page</a>.
> </p>
> </body>
> </html>
>

**Comment by mike-levenick** [comment]
Are you attempting to update the membership of a static group? 

If so, it is a cosmetic/messaging issue. The endpoint it is actually hitting is the group endpoint, and then the serial is in the XML. It is saying that the static group does not yet exist.

You must first manually create a static group, and then populate the CSV with the ID of the static group in Column B. 

I'll work on a 4.2 with improved messaging on this subject.
