### ISSUE TITLE
User Extension Attribute not updating

### ISSUE THREAD

**Issue by seanism** [mike-levenick/mut#9]
I created a CSV with all my users and the data for the user extension attribute.  I set attribute ID which I get from the URL when I view the attribute.  I run the update and it says it worked but nothing shows up in JAMF.  Any thoughts?  Thanks in advance.

CSV: /Users/seanyoung/Downloads/JAMF_OFFICE.csv
Found 292 rows in the CSV.

Example row from your CSV:
Username: adam.levinson, User Extension Attribute: HQ

Device Type: Users
ID Type: Username
Attribute Type: User Extension Attribute

Beginning Update Run!

Device with name adam - OK! - 201
Device with name adam.levinson - OK! - 201
Device with name adam.lohr - OK! - 201

**Comment by mike-levenick** [comment]
Hey Sean, thanks for reaching out. 

I looked over my code and everything looks good, so I tried an extension attribute update via the API in terminal, and I got similar results--everything looks good, but no actual update takes place.

I'll keep digging in on my end, but I also suggest reaching out to Jamf and get a case created to see if they have any more information about User Extension Attributes not updating properly from the API.

**Comment by garavs** [comment]
Mike,
I talked to you about this feature back at JNUC and we had it work then but I haven't been able to since. It had something to do with using the user id.

**Comment by mike-levenick** [comment]
@bumbletech good to see you! Love your work, and glad you're keeping in touch. 

I have to be a bit delicate with my overlap as a Jamf employee in addition to my work outside Jamf on MUT, but from what I'm seeing, PI-003359 is unrelated to this issue.

That said, from the release notes of 10.1 beta, I see under bug fixes and enhancements: 

> [PI-004025] Fixed an issue that resulted in the API failing to modify the user extension attribute values when a user was created.

I am doing some independent testing currently to verify that it is functioning properly in 10.1 beta. Will report back as I find out more.

**Comment by mike-levenick** [comment]
I have tested and confirmed that in Jamf Pro v10.1 beta, MUT is able to update user extension attributes. 

Please let me know if anyone is finding something different.

**Comment by garavs** [comment]
How did you run it?

Anna

**Comment by mike-levenick** [comment]
The beta installer for 10.1 can be found in JamfNation under Assets if you are part of the beta program. If you are not yet, you can request to join the beta program. 

From there, I filled out the dropdowns as follows: 
I want to update: Users
Unique Identifier: Username
Attribute to update: User Extension Attribute
Extension Attribute ID: 5 (this may be different for you). 

CSV file was username in column A, and value for the EA in column B.

**Comment by garavs** [comment]
the ext attribute id is the number from the url for the user, correct?

**Comment by mike-levenick** [comment]
Yup! Right here:

![screen shot 2017-11-20 at 10 44 23 am](https://user-images.githubusercontent.com/12515543/33030046-dbce3228-cddf-11e7-9e03-e39d0fa37abf.png)

**Comment by garavs** [comment]
I swear I'm doing the same thing but it will not update my EA on 10.0.0

**Comment by mike-levenick** [comment]
Correct. 

From the release notes of Jamf Pro v10.1 beta, I see under bug fixes and enhancements:

[PI-004025] Fixed an issue that resulted in the API failing to modify the user extension attribute values

**Comment by garavs** [comment]
Hurray! It works for me now that I've updated to 10.1.1! 
THANK YOU THANK YOU THANK YOU

**Comment by mike-levenick** [comment]
Excellent, I'm glad to hear it!
